REQUIRED_KEYS_FOR_GET_RFAI_EVENT = ["resource", "httpMethod", "queryStringParameters"]
REQUIRED_KEYS_FOR_GET_RFAI_SUMMARY_EVENT = ["resource", "httpMethod"]
REQUIRED_KEYS_FOR_GET_STAKE_FOR_REQUEST_EVENT = ["resource", "httpMethod"]
REQUIRED_KEYS_FOR_GET_SOLUTION_FOR_REQUEST_EVENT = ["resource", "httpMethod", "pathParameters"]
REQUIRED_KEYS_FOR_GET_VOTE_FOR_REQUEST_EVENT = ["resource", "httpMethod", "pathParameters"]